package com.nbloi.cqrses.commonapi.enums;

public enum EventType {
    ORDER_CREATED_EVENT, ORDER_CONFIRMED_EVENT, ORDER_SHIPPED_EVENT,
    PRODUCT_INVENTORY_UPDATED_EVENT, PRODUCT_CREATED_EVENT, PRODUCT_DETAILS_UPDATED_EVENT,
    PAYMENT_COMPLETED_EVENT, PAYMENT_CANCELLED_EVENT, PAYMENT_REFUNDED_EVENT, PAYMENT_REFUNDED_CANCELLED_EVENT,
    PAYMENT_FAILED_EVENT, PAYMENT_FAILED_CANCELLED_EVENT,
    CUSTOMER_PRODUCT_RATED_EVENT
}
