package com.nbloi.cqrses.commonapi.enums;

public enum EventType {
    ORDER_CREATED_EVENT, ORDER_CONFIRMED_EVENT, ORDER_SHIPPED_EVENT, ORDER_CANCELLED_EVENT, ORDER_DELETED_EVENT, ORDER_UPDATED_EVENT,
    PRODUCT_INVENTORY_UPDATED_EVENT, PRODUCT_CREATED_EVENT, PRODUCT_DETAILS_UPDATED_EVENT, PRODUCT_INVENTORY_REVERTED_EVENT, PRODUCT_DELETED_EVENT,
    PAYMENT_CREATED_EVENT, PAYMENT_COMPLETED_EVENT, PAYMENT_CANCELLED_EVENT, PAYMENT_FAILED_EVENT,
    PAYMENT_REFUNDED_CANCELLED_EVENT, PAYMENT_REFUNDED_EVENT, PAYMENT_FAILED_CANCELLED_EVENT,
    CUSTOMER_PRODUCT_RATED_EVENT, PAYMENT_SUMMARIZED_EVENT, PRODUCT_SALES_EVENT, CUSTOMER_ORDER_SUMMARY_EVENT,
    CUSTOMER_CREATED_EVENT, CUSTOMER_UPDATED_EVENT, CUSTOMER_DELETED_EVENT
}
